sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: df42d720e918f40dfd85509bd2b3cf35982dfd2cfd54a580eed9aa399b98ed8d
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=df42d720e918f40dfd85509bd2b3cf35982dfd2cfd54a580eed9aa399b98ed8d bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=df42d720e918f40dfd85509bd2b3cf35982dfd2cfd54a580eed9aa399b98ed8d bundle exec cucumber
